services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - my_network

  tomcat:
    build:
      context: ./tomcat
    ports:
      - "8085:8080"
      - "9010:9010"
      - "1099:1099"    
    environment:
      - JAVA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.rmi.port=1099 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost      
    depends_on:
      - mysql
      - python-service
    networks:
      - my_network

  python-service:
    build:
      context: ./python-service
    ports:
      - "5000:5000"
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:
