receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  
  mysql:
    endpoint: ht-mysql:3306
    username: myuser
    password: mypassword
    database: mydatabase
    collection_interval: 10s
    initial_delay: 1s    
    statement_events:
      digest_text_limit: 120
      time_limit: 24h
      limit: 250

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: "http://ht-jaeger:4317"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug,otlp]
    
    metrics:
      receivers: [otlp,mysql]
      processors: [batch]
      exporters: [debug]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
